#!/usr/bin/env python3
"""
Formats an email digest from recent experiment logs and the evidence ledger.
Usage: python email_format.py [--last-n-cycles 5] [--experiment-log-dir experiment_log/]
Outputs markdown-formatted digest to stdout.
"""
import argparse
import json
import os
import re
import glob


def parse_args():
    parser = argparse.ArgumentParser(description="Generate email digest")
    parser.add_argument("--last-n-cycles", type=int, default=5,
                        help="Number of recent cycles to include")
    parser.add_argument("--experiment-log-dir", default="experiment_log/",
                        help="Path to experiment log directory")
    parser.add_argument("--evidence-ledger", default="evidence_ledger.md",
                        help="Path to evidence ledger")
    return parser.parse_args()


def read_experiment_logs(log_dir, last_n):
    """Read the most recent N experiment log files."""
    pattern = os.path.join(log_dir, "exp_*.md")
    files = sorted(glob.glob(pattern))
    recent = files[-last_n:] if len(files) >= last_n else files
    logs = []
    for f in recent:
        with open(f) as fh:
            logs.append({"file": os.path.basename(f), "content": fh.read()})
    return logs


def read_latest_status(log_dir):
    """Read latest_status.json if it exists."""
    status_path = os.path.join(log_dir, "latest_status.json")
    if os.path.exists(status_path):
        with open(status_path) as f:
            return json.load(f)
    return None


def extract_ledger_summary(ledger_path):
    """Extract the Current Summary section from the evidence ledger."""
    if not os.path.exists(ledger_path):
        return "(evidence ledger not found)"
    with open(ledger_path) as f:
        content = f.read()
    # Extract everything up to the first "---" separator
    parts = content.split("---", 1)
    return parts[0].strip() if parts else content[:2000]


def format_digest(logs, status, ledger_summary, last_n):
    """Format the email digest as markdown."""
    lines = []
    lines.append("# Research Agent Digest")
    lines.append("")

    # Overall status
    if status:
        cycle = status.get("cycle", "?")
        lines.append(f"**Cycles completed:** {cycle}")
        lines.append(f"**Last cycle type:** {status.get('type', 'unknown')}")
        lines.append("")

    # Evidence summary
    lines.append("## Current Evidence Status")
    lines.append("")
    lines.append(ledger_summary)
    lines.append("")

    # Progress bars
    if status and "progress" in status:
        lines.append("## Progress Overview")
        lines.append("")
        for claim, info in status["progress"].items():
            bar_val = info.get("bar", 0)
            filled = "\u25a0" * bar_val + "\u25a1" * (5 - bar_val)
            claim_display = claim.replace("_", " ").title()
            lines.append(f"- {filled} **{claim_display}**: {info.get('status', '?')}")
        lines.append("")

    # Recent experiment summaries
    lines.append(f"## Last {last_n} Cycles")
    lines.append("")
    if not logs:
        lines.append("(no experiment logs found)")
    else:
        for log in reversed(logs):
            lines.append(f"### {log['file']}")
            # Show first 500 chars of each log
            preview = log["content"][:500]
            if len(log["content"]) > 500:
                preview += "\n...(truncated)"
            lines.append(preview)
            lines.append("")

    # Flags for attention
    lines.append("## Flags for Human Attention")
    lines.append("")
    flags_found = False
    for log in logs:
        content_lower = log["content"].lower()
        if any(kw in content_lower for kw in ["needs human review", "unexpected",
                                                "contradiction", "flag", "error",
                                                "failed", "limitation"]):
            lines.append(f"- **{log['file']}** may need review (contains flagged keywords)")
            flags_found = True
    if not flags_found:
        lines.append("(none)")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by the autonomous research agent*")

    return "\n".join(lines)


def main():
    args = parse_args()
    logs = read_experiment_logs(args.experiment_log_dir, args.last_n_cycles)
    status = read_latest_status(args.experiment_log_dir)
    ledger_summary = extract_ledger_summary(args.evidence_ledger)
    digest = format_digest(logs, status, ledger_summary, args.last_n_cycles)
    print(digest)


if __name__ == "__main__":
    main()
